version: "3.4"

services:
  db:
    image: wayfair/postgres
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: -c wal_level=logical -c shared_preload_libraries=wal2json
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
